=begin
#Extend API Reference

## Introduction Welcome to the Extend API Documentation! Our goal is to make your integration as clear and easy as possible, so if you have feedback or suggestions for our API or reference docs, [please let us know](mailto:devs@helloextend.com).    If you are implementing the API for the first time, please use the latest \"2019-08-01\" API version. If you have already implemented the API and haven't specified a version, you are on the \"Default\" API version.   #### You can get up and running with Extend with just 5 simple steps:  *   Create an account with Extend, and get an access token from your Extend merchant portal  *   Sync your store's products to Extend *   Get the relevant Extend warranty SKUs and add them to your store  *   Add the JS SDK snippets to your store's website, which will enable warranty offers to be displayed in your store  *   Record warranty purchases with Extend so we can create a new contract and deliver it to the customer, or record warranty returns / refunds so we can cancel the contract and account for the refunded amount  <div class='wrapper tip'><h2>Pro Tip! Keep your store's products up to date</h2><p>To make sure you are selling warranty plans on all eligible products (and not selling them on ineligible ones), it is best to keep your store's products in sync with Extend. If you update your products infrequently, it might be easiest to manually upload or edit products in your merchant portal. If you do update frequently, though, consider integrating with our Products API resource.</p><p>Need help? <a href='mailto:devs@helloextend.com'>Contact us!</a> We love to help!</p></div>

The version of the OpenAPI document: Default

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1-SNAPSHOT

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/address'
require 'openapi_client/models/amount'
require 'openapi_client/models/contract'
require 'openapi_client/models/contract_plan'
require 'openapi_client/models/contract_product'
require 'openapi_client/models/customer'
require 'openapi_client/models/error'
require 'openapi_client/models/invoice'
require 'openapi_client/models/invoice_details'
require 'openapi_client/models/invoice_discount'
require 'openapi_client/models/invoice_items'
require 'openapi_client/models/invoice_metadata'
require 'openapi_client/models/invoice_metadata_product'
require 'openapi_client/models/invoice_payee'
require 'openapi_client/models/invoice_payer'
require 'openapi_client/models/offer'
require 'openapi_client/models/offer_plan'
require 'openapi_client/models/offer_plan_contract'
require 'openapi_client/models/plan'
require 'openapi_client/models/plan_details'
require 'openapi_client/models/plan_prices'
require 'openapi_client/models/plans_list'
require 'openapi_client/models/product'
require 'openapi_client/models/product_identifiers'
require 'openapi_client/models/product_mfr_warranty'

# APIs
require 'openapi_client/api/contracts_api'
require 'openapi_client/api/offers_api'
require 'openapi_client/api/plans_api'
require 'openapi_client/api/products_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
